/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdTasksIndexRouteImport } from './routes/projects/$projectId/tasks/index'
import { Route as ProjectsProjectIdTasksTaskIdIndexRouteImport } from './routes/projects/$projectId/tasks/$taskId/index'
import { Route as ProjectsProjectIdTasksNewIndexRouteImport } from './routes/projects/$projectId/tasks/new/index'
import { Route as ProjectsProjectIdTasksTaskIdEditIndexRouteImport } from './routes/projects/$projectId/tasks/$taskId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdTasksIndexRoute =
  ProjectsProjectIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTasksTaskIdIndexRoute =
  ProjectsProjectIdTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTasksNewIndexRoute =
  ProjectsProjectIdTasksNewIndexRouteImport.update({
    id: '/tasks/new/',
    path: '/tasks/new/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdTasksTaskIdEditIndexRoute =
  ProjectsProjectIdTasksTaskIdEditIndexRouteImport.update({
    id: '/tasks/$taskId/edit/',
    path: '/tasks/$taskId/edit/',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks/': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/tasks/$taskId/': typeof ProjectsProjectIdTasksTaskIdIndexRoute
  '/projects/$projectId/tasks/new/': typeof ProjectsProjectIdTasksNewIndexRoute
  '/projects/$projectId/tasks/$taskId/edit/': typeof ProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/tasks/$taskId': typeof ProjectsProjectIdTasksTaskIdIndexRoute
  '/projects/$projectId/tasks/new': typeof ProjectsProjectIdTasksNewIndexRoute
  '/projects/$projectId/tasks/$taskId/edit': typeof ProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/tasks/': typeof ProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/tasks/$taskId/': typeof ProjectsProjectIdTasksTaskIdIndexRoute
  '/projects/$projectId/tasks/new/': typeof ProjectsProjectIdTasksNewIndexRoute
  '/projects/$projectId/tasks/$taskId/edit/': typeof ProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/tasks/$taskId/'
    | '/projects/$projectId/tasks/new/'
    | '/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/tasks/new'
    | '/projects/$projectId/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/tasks/$taskId/'
    | '/projects/$projectId/tasks/new/'
    | '/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/tasks/': {
      id: '/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks/'
      preLoaderRoute: typeof ProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/tasks/$taskId/': {
      id: '/projects/$projectId/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId/'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/tasks/new/': {
      id: '/projects/$projectId/tasks/new/'
      path: '/tasks/new'
      fullPath: '/projects/$projectId/tasks/new/'
      preLoaderRoute: typeof ProjectsProjectIdTasksNewIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/tasks/$taskId/edit/': {
      id: '/projects/$projectId/tasks/$taskId/edit/'
      path: '/tasks/$taskId/edit'
      fullPath: '/projects/$projectId/tasks/$taskId/edit/'
      preLoaderRoute: typeof ProjectsProjectIdTasksTaskIdEditIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdTasksIndexRoute: typeof ProjectsProjectIdTasksIndexRoute
  ProjectsProjectIdTasksTaskIdIndexRoute: typeof ProjectsProjectIdTasksTaskIdIndexRoute
  ProjectsProjectIdTasksNewIndexRoute: typeof ProjectsProjectIdTasksNewIndexRoute
  ProjectsProjectIdTasksTaskIdEditIndexRoute: typeof ProjectsProjectIdTasksTaskIdEditIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdTasksIndexRoute: ProjectsProjectIdTasksIndexRoute,
    ProjectsProjectIdTasksTaskIdIndexRoute:
      ProjectsProjectIdTasksTaskIdIndexRoute,
    ProjectsProjectIdTasksNewIndexRoute: ProjectsProjectIdTasksNewIndexRoute,
    ProjectsProjectIdTasksTaskIdEditIndexRoute:
      ProjectsProjectIdTasksTaskIdEditIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
