/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AngularIndexRouteImport } from './routes/angular/index'
import { Route as ReactIndexRouteImport } from './routes/react/index'
import { Route as VueIndexRouteImport } from './routes/vue/index'
import { Route as ReactProjectsIndexRouteImport } from './routes/react/projects/index'
import { Route as ReactProjectsProjectIdRouteRouteImport } from './routes/react/projects/$projectId/route'
import { Route as ReactWizardIndexRouteImport } from './routes/react/wizard/index'
import { Route as ReactProjectsProjectIdIndexRouteImport } from './routes/react/projects/$projectId/index'
import { Route as ReactProjectsProjectIdTasksIndexRouteImport } from './routes/react/projects/$projectId/tasks/index'
import { Route as ReactProjectsProjectIdTasksTaskIdIndexRouteImport } from './routes/react/projects/$projectId/tasks/$taskId/index'
import { Route as ReactProjectsProjectIdTasksNewIndexRouteImport } from './routes/react/projects/$projectId/tasks/new/index'
import { Route as ReactProjectsProjectIdTasksTaskIdEditIndexRouteImport } from './routes/react/projects/$projectId/tasks/$taskId/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AngularIndexRoute = AngularIndexRouteImport.update({
  id: '/angular/',
  path: '/angular/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactIndexRoute = ReactIndexRouteImport.update({
  id: '/react/',
  path: '/react/',
  getParentRoute: () => rootRouteImport,
} as any)
const VueIndexRoute = VueIndexRouteImport.update({
  id: '/vue/',
  path: '/vue/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactProjectsIndexRoute = ReactProjectsIndexRouteImport.update({
  id: '/react/projects/',
  path: '/react/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactProjectsProjectIdRouteRoute =
  ReactProjectsProjectIdRouteRouteImport.update({
    id: '/react/projects/$projectId',
    path: '/react/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReactWizardIndexRoute = ReactWizardIndexRouteImport.update({
  id: '/react/wizard/',
  path: '/react/wizard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactProjectsProjectIdIndexRoute =
  ReactProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ReactProjectsProjectIdRouteRoute,
  } as any)
const ReactProjectsProjectIdTasksIndexRoute =
  ReactProjectsProjectIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => ReactProjectsProjectIdRouteRoute,
  } as any)
const ReactProjectsProjectIdTasksTaskIdIndexRoute =
  ReactProjectsProjectIdTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => ReactProjectsProjectIdRouteRoute,
  } as any)
const ReactProjectsProjectIdTasksNewIndexRoute =
  ReactProjectsProjectIdTasksNewIndexRouteImport.update({
    id: '/tasks/new/',
    path: '/tasks/new/',
    getParentRoute: () => ReactProjectsProjectIdRouteRoute,
  } as any)
const ReactProjectsProjectIdTasksTaskIdEditIndexRoute =
  ReactProjectsProjectIdTasksTaskIdEditIndexRouteImport.update({
    id: '/tasks/$taskId/edit/',
    path: '/tasks/$taskId/edit/',
    getParentRoute: () => ReactProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/angular/': typeof AngularIndexRoute
  '/react/': typeof ReactIndexRoute
  '/vue/': typeof VueIndexRoute
  '/react/projects/$projectId': typeof ReactProjectsProjectIdRouteRouteWithChildren
  '/react/projects/': typeof ReactProjectsIndexRoute
  '/react/wizard/': typeof ReactWizardIndexRoute
  '/react/projects/$projectId/': typeof ReactProjectsProjectIdIndexRoute
  '/react/projects/$projectId/tasks/': typeof ReactProjectsProjectIdTasksIndexRoute
  '/react/projects/$projectId/tasks/$taskId/': typeof ReactProjectsProjectIdTasksTaskIdIndexRoute
  '/react/projects/$projectId/tasks/new/': typeof ReactProjectsProjectIdTasksNewIndexRoute
  '/react/projects/$projectId/tasks/$taskId/edit/': typeof ReactProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/angular': typeof AngularIndexRoute
  '/react': typeof ReactIndexRoute
  '/vue': typeof VueIndexRoute
  '/react/projects': typeof ReactProjectsIndexRoute
  '/react/wizard': typeof ReactWizardIndexRoute
  '/react/projects/$projectId': typeof ReactProjectsProjectIdIndexRoute
  '/react/projects/$projectId/tasks': typeof ReactProjectsProjectIdTasksIndexRoute
  '/react/projects/$projectId/tasks/$taskId': typeof ReactProjectsProjectIdTasksTaskIdIndexRoute
  '/react/projects/$projectId/tasks/new': typeof ReactProjectsProjectIdTasksNewIndexRoute
  '/react/projects/$projectId/tasks/$taskId/edit': typeof ReactProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/angular/': typeof AngularIndexRoute
  '/react/': typeof ReactIndexRoute
  '/vue/': typeof VueIndexRoute
  '/react/projects/$projectId': typeof ReactProjectsProjectIdRouteRouteWithChildren
  '/react/projects/': typeof ReactProjectsIndexRoute
  '/react/wizard/': typeof ReactWizardIndexRoute
  '/react/projects/$projectId/': typeof ReactProjectsProjectIdIndexRoute
  '/react/projects/$projectId/tasks/': typeof ReactProjectsProjectIdTasksIndexRoute
  '/react/projects/$projectId/tasks/$taskId/': typeof ReactProjectsProjectIdTasksTaskIdIndexRoute
  '/react/projects/$projectId/tasks/new/': typeof ReactProjectsProjectIdTasksNewIndexRoute
  '/react/projects/$projectId/tasks/$taskId/edit/': typeof ReactProjectsProjectIdTasksTaskIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/angular/'
    | '/react/'
    | '/vue/'
    | '/react/projects/$projectId'
    | '/react/projects/'
    | '/react/wizard/'
    | '/react/projects/$projectId/'
    | '/react/projects/$projectId/tasks/'
    | '/react/projects/$projectId/tasks/$taskId/'
    | '/react/projects/$projectId/tasks/new/'
    | '/react/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/angular'
    | '/react'
    | '/vue'
    | '/react/projects'
    | '/react/wizard'
    | '/react/projects/$projectId'
    | '/react/projects/$projectId/tasks'
    | '/react/projects/$projectId/tasks/$taskId'
    | '/react/projects/$projectId/tasks/new'
    | '/react/projects/$projectId/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/angular/'
    | '/react/'
    | '/vue/'
    | '/react/projects/$projectId'
    | '/react/projects/'
    | '/react/wizard/'
    | '/react/projects/$projectId/'
    | '/react/projects/$projectId/tasks/'
    | '/react/projects/$projectId/tasks/$taskId/'
    | '/react/projects/$projectId/tasks/new/'
    | '/react/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  AngularIndexRoute: typeof AngularIndexRoute
  ReactIndexRoute: typeof ReactIndexRoute
  VueIndexRoute: typeof VueIndexRoute
  ReactProjectsProjectIdRouteRoute: typeof ReactProjectsProjectIdRouteRouteWithChildren
  ReactProjectsIndexRoute: typeof ReactProjectsIndexRoute
  ReactWizardIndexRoute: typeof ReactWizardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angular/': {
      id: '/angular/'
      path: '/angular'
      fullPath: '/angular/'
      preLoaderRoute: typeof AngularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/': {
      id: '/react/'
      path: '/react'
      fullPath: '/react/'
      preLoaderRoute: typeof ReactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vue/': {
      id: '/vue/'
      path: '/vue'
      fullPath: '/vue/'
      preLoaderRoute: typeof VueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/projects/': {
      id: '/react/projects/'
      path: '/react/projects'
      fullPath: '/react/projects/'
      preLoaderRoute: typeof ReactProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/projects/$projectId': {
      id: '/react/projects/$projectId'
      path: '/react/projects/$projectId'
      fullPath: '/react/projects/$projectId'
      preLoaderRoute: typeof ReactProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/wizard/': {
      id: '/react/wizard/'
      path: '/react/wizard'
      fullPath: '/react/wizard/'
      preLoaderRoute: typeof ReactWizardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react/projects/$projectId/': {
      id: '/react/projects/$projectId/'
      path: '/'
      fullPath: '/react/projects/$projectId/'
      preLoaderRoute: typeof ReactProjectsProjectIdIndexRouteImport
      parentRoute: typeof ReactProjectsProjectIdRouteRoute
    }
    '/react/projects/$projectId/tasks/': {
      id: '/react/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/react/projects/$projectId/tasks/'
      preLoaderRoute: typeof ReactProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof ReactProjectsProjectIdRouteRoute
    }
    '/react/projects/$projectId/tasks/$taskId/': {
      id: '/react/projects/$projectId/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/react/projects/$projectId/tasks/$taskId/'
      preLoaderRoute: typeof ReactProjectsProjectIdTasksTaskIdIndexRouteImport
      parentRoute: typeof ReactProjectsProjectIdRouteRoute
    }
    '/react/projects/$projectId/tasks/new/': {
      id: '/react/projects/$projectId/tasks/new/'
      path: '/tasks/new'
      fullPath: '/react/projects/$projectId/tasks/new/'
      preLoaderRoute: typeof ReactProjectsProjectIdTasksNewIndexRouteImport
      parentRoute: typeof ReactProjectsProjectIdRouteRoute
    }
    '/react/projects/$projectId/tasks/$taskId/edit/': {
      id: '/react/projects/$projectId/tasks/$taskId/edit/'
      path: '/tasks/$taskId/edit'
      fullPath: '/react/projects/$projectId/tasks/$taskId/edit/'
      preLoaderRoute: typeof ReactProjectsProjectIdTasksTaskIdEditIndexRouteImport
      parentRoute: typeof ReactProjectsProjectIdRouteRoute
    }
  }
}

interface ReactProjectsProjectIdRouteRouteChildren {
  ReactProjectsProjectIdIndexRoute: typeof ReactProjectsProjectIdIndexRoute
  ReactProjectsProjectIdTasksIndexRoute: typeof ReactProjectsProjectIdTasksIndexRoute
  ReactProjectsProjectIdTasksTaskIdIndexRoute: typeof ReactProjectsProjectIdTasksTaskIdIndexRoute
  ReactProjectsProjectIdTasksNewIndexRoute: typeof ReactProjectsProjectIdTasksNewIndexRoute
  ReactProjectsProjectIdTasksTaskIdEditIndexRoute: typeof ReactProjectsProjectIdTasksTaskIdEditIndexRoute
}

const ReactProjectsProjectIdRouteRouteChildren: ReactProjectsProjectIdRouteRouteChildren =
  {
    ReactProjectsProjectIdIndexRoute: ReactProjectsProjectIdIndexRoute,
    ReactProjectsProjectIdTasksIndexRoute:
      ReactProjectsProjectIdTasksIndexRoute,
    ReactProjectsProjectIdTasksTaskIdIndexRoute:
      ReactProjectsProjectIdTasksTaskIdIndexRoute,
    ReactProjectsProjectIdTasksNewIndexRoute:
      ReactProjectsProjectIdTasksNewIndexRoute,
    ReactProjectsProjectIdTasksTaskIdEditIndexRoute:
      ReactProjectsProjectIdTasksTaskIdEditIndexRoute,
  }

const ReactProjectsProjectIdRouteRouteWithChildren =
  ReactProjectsProjectIdRouteRoute._addFileChildren(
    ReactProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  AngularIndexRoute: AngularIndexRoute,
  ReactIndexRoute: ReactIndexRoute,
  VueIndexRoute: VueIndexRoute,
  ReactProjectsProjectIdRouteRoute:
    ReactProjectsProjectIdRouteRouteWithChildren,
  ReactProjectsIndexRoute: ReactProjectsIndexRoute,
  ReactWizardIndexRoute: ReactWizardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
