/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as compareCompareDotpageRouteImport } from './routes/compare/compare.page'
import { Route as projectsProjectsDotpageRouteImport } from './routes/projects/projects.page'
import { Route as projectsProjectIdProjectIdDotlayoutRouteImport } from './routes/projects/$projectId/project-id.layout'
import { Route as wizardWizardDotpageRouteImport } from './routes/wizard/wizard.page'
import { Route as projectsProjectIdProjectIdDotpageRouteImport } from './routes/projects/$projectId/project-id.page'
import { Route as projectsProjectIdTasksTasksDotpageRouteImport } from './routes/projects/$projectId/tasks/tasks.page'
import { Route as projectsProjectIdTasksTaskIdTaskIdDotpageRouteImport } from './routes/projects/$projectId/tasks/$taskId/task-id.page'
import { Route as projectsProjectIdTasksNewNewDotpageRouteImport } from './routes/projects/$projectId/tasks/new/new.page'
import { Route as projectsProjectIdTasksTaskIdEditEditDotpageRouteImport } from './routes/projects/$projectId/tasks/$taskId/edit/edit.page'

const compareCompareDotpageRoute = compareCompareDotpageRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const projectsProjectsDotpageRoute = projectsProjectsDotpageRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const projectsProjectIdProjectIdDotlayoutRoute =
  projectsProjectIdProjectIdDotlayoutRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const wizardWizardDotpageRoute = wizardWizardDotpageRouteImport.update({
  id: '/wizard/',
  path: '/wizard/',
  getParentRoute: () => rootRouteImport,
} as any)
const projectsProjectIdProjectIdDotpageRoute =
  projectsProjectIdProjectIdDotpageRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => projectsProjectIdProjectIdDotlayoutRoute,
  } as any)
const projectsProjectIdTasksTasksDotpageRoute =
  projectsProjectIdTasksTasksDotpageRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => projectsProjectIdProjectIdDotlayoutRoute,
  } as any)
const projectsProjectIdTasksTaskIdTaskIdDotpageRoute =
  projectsProjectIdTasksTaskIdTaskIdDotpageRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => projectsProjectIdProjectIdDotlayoutRoute,
  } as any)
const projectsProjectIdTasksNewNewDotpageRoute =
  projectsProjectIdTasksNewNewDotpageRouteImport.update({
    id: '/tasks/new/',
    path: '/tasks/new/',
    getParentRoute: () => projectsProjectIdProjectIdDotlayoutRoute,
  } as any)
const projectsProjectIdTasksTaskIdEditEditDotpageRoute =
  projectsProjectIdTasksTaskIdEditEditDotpageRouteImport.update({
    id: '/tasks/$taskId/edit/',
    path: '/tasks/$taskId/edit/',
    getParentRoute: () => projectsProjectIdProjectIdDotlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/compare/': typeof compareCompareDotpageRoute
  '/projects/': typeof projectsProjectsDotpageRoute
  '/wizard/': typeof wizardWizardDotpageRoute
  '/projects/$projectId': typeof projectsProjectIdProjectIdDotlayoutRouteWithChildren
  '/projects/$projectId/': typeof projectsProjectIdProjectIdDotpageRoute
  '/projects/$projectId/tasks/': typeof projectsProjectIdTasksTasksDotpageRoute
  '/projects/$projectId/tasks/$taskId/': typeof projectsProjectIdTasksTaskIdTaskIdDotpageRoute
  '/projects/$projectId/tasks/new/': typeof projectsProjectIdTasksNewNewDotpageRoute
  '/projects/$projectId/tasks/$taskId/edit/': typeof projectsProjectIdTasksTaskIdEditEditDotpageRoute
}
export interface FileRoutesByTo {
  '/compare': typeof compareCompareDotpageRoute
  '/projects': typeof projectsProjectsDotpageRoute
  '/wizard': typeof wizardWizardDotpageRoute
  '/projects/$projectId': typeof projectsProjectIdProjectIdDotpageRoute
  '/projects/$projectId/tasks': typeof projectsProjectIdTasksTasksDotpageRoute
  '/projects/$projectId/tasks/$taskId': typeof projectsProjectIdTasksTaskIdTaskIdDotpageRoute
  '/projects/$projectId/tasks/new': typeof projectsProjectIdTasksNewNewDotpageRoute
  '/projects/$projectId/tasks/$taskId/edit': typeof projectsProjectIdTasksTaskIdEditEditDotpageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/compare/': typeof compareCompareDotpageRoute
  '/projects/': typeof projectsProjectsDotpageRoute
  '/wizard/': typeof wizardWizardDotpageRoute
  '/projects/$projectId': typeof projectsProjectIdProjectIdDotlayoutRouteWithChildren
  '/projects/$projectId/': typeof projectsProjectIdProjectIdDotpageRoute
  '/projects/$projectId/tasks/': typeof projectsProjectIdTasksTasksDotpageRoute
  '/projects/$projectId/tasks/$taskId/': typeof projectsProjectIdTasksTaskIdTaskIdDotpageRoute
  '/projects/$projectId/tasks/new/': typeof projectsProjectIdTasksNewNewDotpageRoute
  '/projects/$projectId/tasks/$taskId/edit/': typeof projectsProjectIdTasksTaskIdEditEditDotpageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/compare/'
    | '/projects/'
    | '/wizard/'
    | '/projects/$projectId'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/tasks/$taskId/'
    | '/projects/$projectId/tasks/new/'
    | '/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/compare'
    | '/projects'
    | '/wizard'
    | '/projects/$projectId'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tasks/$taskId'
    | '/projects/$projectId/tasks/new'
    | '/projects/$projectId/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/compare/'
    | '/projects/'
    | '/wizard/'
    | '/projects/$projectId'
    | '/projects/$projectId/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/tasks/$taskId/'
    | '/projects/$projectId/tasks/new/'
    | '/projects/$projectId/tasks/$taskId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  compareCompareDotpageRoute: typeof compareCompareDotpageRoute
  projectsProjectsDotpageRoute: typeof projectsProjectsDotpageRoute
  wizardWizardDotpageRoute: typeof wizardWizardDotpageRoute
  projectsProjectIdProjectIdDotlayoutRoute: typeof projectsProjectIdProjectIdDotlayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof compareCompareDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof projectsProjectsDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof projectsProjectIdProjectIdDotlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wizard/': {
      id: '/wizard/'
      path: '/wizard'
      fullPath: '/wizard/'
      preLoaderRoute: typeof wizardWizardDotpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof projectsProjectIdProjectIdDotpageRouteImport
      parentRoute: typeof projectsProjectIdProjectIdDotlayoutRoute
    }
    '/projects/$projectId/tasks/': {
      id: '/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks/'
      preLoaderRoute: typeof projectsProjectIdTasksTasksDotpageRouteImport
      parentRoute: typeof projectsProjectIdProjectIdDotlayoutRoute
    }
    '/projects/$projectId/tasks/$taskId/': {
      id: '/projects/$projectId/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId/'
      preLoaderRoute: typeof projectsProjectIdTasksTaskIdTaskIdDotpageRouteImport
      parentRoute: typeof projectsProjectIdProjectIdDotlayoutRoute
    }
    '/projects/$projectId/tasks/new/': {
      id: '/projects/$projectId/tasks/new/'
      path: '/tasks/new'
      fullPath: '/projects/$projectId/tasks/new/'
      preLoaderRoute: typeof projectsProjectIdTasksNewNewDotpageRouteImport
      parentRoute: typeof projectsProjectIdProjectIdDotlayoutRoute
    }
    '/projects/$projectId/tasks/$taskId/edit/': {
      id: '/projects/$projectId/tasks/$taskId/edit/'
      path: '/tasks/$taskId/edit'
      fullPath: '/projects/$projectId/tasks/$taskId/edit/'
      preLoaderRoute: typeof projectsProjectIdTasksTaskIdEditEditDotpageRouteImport
      parentRoute: typeof projectsProjectIdProjectIdDotlayoutRoute
    }
  }
}

interface projectsProjectIdProjectIdDotlayoutRouteChildren {
  projectsProjectIdProjectIdDotpageRoute: typeof projectsProjectIdProjectIdDotpageRoute
  projectsProjectIdTasksTasksDotpageRoute: typeof projectsProjectIdTasksTasksDotpageRoute
  projectsProjectIdTasksTaskIdTaskIdDotpageRoute: typeof projectsProjectIdTasksTaskIdTaskIdDotpageRoute
  projectsProjectIdTasksNewNewDotpageRoute: typeof projectsProjectIdTasksNewNewDotpageRoute
  projectsProjectIdTasksTaskIdEditEditDotpageRoute: typeof projectsProjectIdTasksTaskIdEditEditDotpageRoute
}

const projectsProjectIdProjectIdDotlayoutRouteChildren: projectsProjectIdProjectIdDotlayoutRouteChildren =
  {
    projectsProjectIdProjectIdDotpageRoute:
      projectsProjectIdProjectIdDotpageRoute,
    projectsProjectIdTasksTasksDotpageRoute:
      projectsProjectIdTasksTasksDotpageRoute,
    projectsProjectIdTasksTaskIdTaskIdDotpageRoute:
      projectsProjectIdTasksTaskIdTaskIdDotpageRoute,
    projectsProjectIdTasksNewNewDotpageRoute:
      projectsProjectIdTasksNewNewDotpageRoute,
    projectsProjectIdTasksTaskIdEditEditDotpageRoute:
      projectsProjectIdTasksTaskIdEditEditDotpageRoute,
  }

const projectsProjectIdProjectIdDotlayoutRouteWithChildren =
  projectsProjectIdProjectIdDotlayoutRoute._addFileChildren(
    projectsProjectIdProjectIdDotlayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  compareCompareDotpageRoute: compareCompareDotpageRoute,
  projectsProjectsDotpageRoute: projectsProjectsDotpageRoute,
  wizardWizardDotpageRoute: wizardWizardDotpageRoute,
  projectsProjectIdProjectIdDotlayoutRoute:
    projectsProjectIdProjectIdDotlayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
